### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by sandroandrade**
This PR adds CMake build support for The Forge libraries (OS and Renderer), unit tests, and the AssetPipelineCmd utility (desktop platforms only).

This has been tested on:
* Arch Linux (6.10 kernel, g++ 14, and clang++ 18)
* Windows 11 (MSVC 2019)
* macOS 14.5 (Xcode 15.4 / clang++ 15)
* Android (NDK 26.1.10909125)
* iOS (Xcode 15.4 / clang++ 15)

**NOTE:** This PR contains no source code changes. A couple of directories have been renamed to fix typos and improve consistency:

* `Examples_3/Unit_Tests/macOS Xcode/14_WaveIntrinsincs/` renamed to `Examples_3/Unit_Tests/macOS Xcode/14_WaveIntrinsics/`
* `Examples_3/Unit_Tests/macOS Xcode/19_CodeHotReload_Main/` renamed to `Examples_3/Unit_Tests/macOS Xcode/19_CodeHotReload/`

Important information:

* Unit tests and AssetPipelineCmd builds can be disabled by setting CMake variables `BUILD_UNIT_TESTS` and `BUILD_ASSETPIPELINECMD` to `OFF` (default is `ON`).
* The CMake implementation has been checked with `cmake-lint` and `cmake-format` tools from [cmakelang](https://pypi.org/project/cmakelang/).
* Specific builds have been created for the following libraries: `OS`, `Renderer`, `ozz_base`, `ozz_animation`, `ozz_animation_offline`, `gainput`, `SpirVTools`, `ispc_texcomp`, and `Buny`, along with their dependencies.
* Shaders are automatically processed with FSL and redeployed when any changes are made to `.fsl` files.
* `cmake/TheForgeUtils.cmake` provides new functions that make it easy to add new unit tests and shaders in the future.
* A new section has been added into `README.md` with CMake build instructions.
* `Art.zip` is automatically downloaded at first CMake run.

Known issues:
* Direct3D11 usage: The FSL tool is currently unable to generate/compile D3D11 implementations. This PR currently enables D3D12 for Windows builds.
* Release mode on Linux: Everything builds fine, but unit tests fail at runtime with: "Office preset is not supported by The Forge." Debug mode works fine.
* Linux with `vulkan-icd-loader` 1.3.285: Unit tests crash with this package version. They work fine with 1.3.279. Reported [here](https://github.com/ConfettiFX/The-Forge/issues/309).
* Support for Android/iOS package creation and deployment for unit tests: This PR currently does not implement Android/iOS package creation and deployment to devices. I see some assets for that purpose at `Common_3/OS/Android/Packaging/`. I could work on this as a future task if you find it worthwhile.

Credits: this was developed while working at Buildbox/AppOnboard. Thanks to Adam Piechowicz for reviewing and suggestions.

### CODE REVIEW

**Comment by sandroandrade** [comment]
Hi Wolfgang,

Would you mind providing any feedback or reasons for closing this pull request?

Thanks,

**Comment by JonahGoldsmith** [comment]
Sandro I am not affiliated with The-Forge but im pretty sure the closed it because they don't want to support CMAKE in the official github repository... many people have tried to create branches/PR's and they always get turned into forks instead of merging

**Comment by sandroandrade** [comment]
Hi Jonah,

Thanks for your comment; I appreciate it. If ConfettiFX expects external contributions for this project, it would be helpful to have some contribution guidelines outlining wanted and unwanted features. Also, silently closing PRs with no minimal feedback doesn't sound like a community-friendly stance.
